In [1]:
!pip install numpy pandas

In [3]:
import numpy as np

In [6]:
A = [1, 2, 3, 4, 5]
type(A)

list

In [7]:
B = np.array([1, 2, 3, 4, 5])
type(B)

numpy.ndarray

In [8]:
import sys

# size of array
size_array = sys.getsizeof(1) * len(A)
print("Size array A: ", size_array)

Size array A:  140


In [9]:
# size of numpy array
size_numpy = B.itemsize * B.size
print("Size numpy: ", size_numpy)

Size numpy:  40


In [11]:
# A matrix of 2 * 5 
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
A.shape

(2, 5)

In [14]:
A.flatten().shape

(10,)

In [29]:
A.reshape(1, 1, -1).shape

(1, 1, 10)

In [21]:
A.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [22]:
A.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [34]:
B = np.arange(0, 100)
B.shape

(100,)

In [37]:
B.reshape(4, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
zeros = np.zeros([10, 2])
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
ones = np.ones([10, 1])
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [43]:
A = np.arange(0, 100).reshape(-1, 1).flatten()
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
A = np.array([1, 2, 3])
A * 2

array([2, 4, 6])

In [47]:
B = np.array([4, 5, 6])
A + B

array([5, 7, 9])

In [49]:
A

array([1, 2, 3])

In [51]:
C = [1, 1, 1, 1]
C + A 

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [52]:
print(A, B)

[1 2 3] [4 5 6]


In [53]:
A * B

array([ 4, 10, 18])

In [54]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [56]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [57]:
print(A)

[1 2 3]


In [58]:
np.mean(A)

2.0

In [59]:
np.median(A)

2.0

In [60]:
A = np.array([1, 2, 0, 4, 5, 6])
C = np.where(A > 2)
C

(array([3, 4, 5]),)

# Dot Product

In [61]:
def dot_product(a, b):
    result = 0
    for i in range(len(a)):
        result = result + a[i]*b[i]
    return result 

In [70]:
np.random.random(5)

array([0.94511124, 0.59463565, 0.9850678 , 0.12467884, 0.36018232])

In [76]:
a = np.random.randn(10000000)
b = np.random.randn(10000000)

In [77]:
import time

start = time.time()

dot_product(a, b)


total = time.time() - start
print("total time: ", total)

total time:  4.017674922943115


In [ ]:
import time

start = time.time()

# dot product with numpy

total = time.time() - start
print("total time: ", total)